### ISSUE TITLE
Prevent deletion of machine and cluster hosting cluster-api's api-server

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-aws#214]
/kind bug

Currently it is possible to delete the Machine Object (and transitively the Instance backing that machine) that is hosting the Control Plane for the cluster that is running the Cluster API CRDs/Controllers. If this happens, then all other Machine Instances and other corresponding AWS resources attached to the Cluster Object are orphaned.

There is some checking within the upstream Cluster API code to avoid deleting a machine in this case, but it is tied to the link between the Node Object and the Machine Object, which I do not believe we are currently handling properly in our provider implementation.

/priority important-soon

**Comment by randomvariable** [comment]
Conversely, deleting the cluster also leads to *fun*/a partially deleted VPC and an inaccessible API server.

**Comment by detiber** [comment]
Created https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/215 to track better handling of deleting a cluster when machines are present.

**Comment by timothysc** [comment]
On pivot, there exists a scenario where you can delete the machine that hosts the api-server.

**Comment by detiber** [comment]
@chuckha ptal at the updated description and let me know if that help clarifies it.

**Comment by vincepri** [comment]
This should be fixed now that #596 and #579 are merged, need some testing which I'll do early next week

**Comment by ncdc** [comment]
@vincepri have you had a chance to test this?

**Comment by ashish-amarnath** [comment]
This is still happening at commit [e01bcd1](https://github.com/kubernetes-sigs/cluster-api-provider-aws/commit/e01bcd1c2275a8f8c429bfe6bdf2696896bb981b)

**Comment by vincepri** [comment]
@ashish-amarnath That's unfortunate :/, in theory this should have been fixed after `NodeRef` PR was merged, although that depends on how you trigger the deletion request. If it's done through `clusterctl` (which I tested) it should work just fine because resources are pivoted back to the ephemeral cluster and then deleted. Can you expand a little on the steps you took and what you saw?

@detiber Do you have more specific requirements on what the actual test should be like? From what I've seen and the tests I've been running locally should suffice to close this issue.

**Comment by ashish-amarnath** [comment]
This is what I did to repro..

$ make create-cluster
# Once the cluster is created and pivoted and kind cluster is deleted
$ kc delete machine controlplane-0

**Comment by vincepri** [comment]
Got it! I think that's separate from this issue, but I'll let Jason chime in. This issue was mostly around delete, which would break if the machine was deleted before pivoting / other resources. I think with NodeRef and ownerRef resources correctly set, the above shouldn't happen.

**Comment by detiber** [comment]
The process for deleting the machine shouldn't matter, the logic is baked into the Machine controller logic in cluster-api: https://github.com/kubernetes-sigs/cluster-api/blob/master/pkg/controller/machine/controller.go#L165, which should prevent deletion as long as the NodeRef is set and the NODE_NAME env variable is set for the manager process, which it looks like we should be doing: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/config/manager/manager.yaml#L74-L78

**Comment by ashish-amarnath** [comment]
I can give this a try and make a PR if required if Vince hasn’t started
already.

**Comment by chuckha** [comment]
@ashish-amarnath If it's not marked as active then you're good to grab it and go for it!

**Comment by ashish-amarnath** [comment]
Added some debug logs in the capi `isDeleteAllowed` method to investigate why deleting the only controlplane machine is being allowed and I see this.
https://github.com/kubernetes-sigs/cluster-api/compare/master...ashish-amarnath:instrumented?expand=1
```(bash)
I0317 04:29:47.303367       1 controller.go:255] reconcilerNodeName: "ip-10-0-0-224.ec2.internal", machineStatusNodeRef: "&ObjectReference{Kind:,Namespace:,Name:ip-10-0-0-224.ec2.internal,UID:,APIVersion:,ResourceVersion:,FieldPath:,}"
I0317 04:29:47.303952       1 reflector.go:131] Starting reflector *v1.Node (10h0m0s) from pkg/cache/internal/informers_map.go:196
I0317 04:29:47.303966       1 reflector.go:169] Listing and watching *v1.Node from pkg/cache/internal/informers_map.go:196
I0317 04:29:47.404131       1 controller.go:274] node.UID: "eab72101-486c-11e9-a3e4-123c969e3df2", machineStatusNodeRefUID: "", isDelete: true
I0317 04:29:47.404164       1 controller.go:170] Reconciling machine "controlplane-0" triggers delete
```

**Comment by detiber** [comment]
It looks like the Node ref that we are creating only has the Name set and we are instead trying to compare on UID....

**Comment by ashish-amarnath** [comment]
@detiber your PR makes sense. I was kinda expecting magic to happen :)
