### ISSUE TITLE
Deleting EC2 Cluster Hangs: The Created VPC is not Deleted

### ISSUE THREAD

**Issue by pfcurtis** [kubernetes-sigs/cluster-api-provider-aws#3810]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
We created an EC2 cluster utilizing the current "clusterctl generate" command. (manifest attached). The cluster was then deleted. The current status shows
```
$ kubectl get clusters
NAME                 PHASE      AGE   VERSION
gartner-group-mgmt   Deleting   8d    

```
The CAPA controller manager logs show:
`I1031 18:41:16.927938       1 awscluster_controller.go:209] controller/awscluster "msg"="Reconciling AWSCluster delete" "cluster"="gartner-group-mgmt" "name"="gartner-group-mgmt" "namespace"="default" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AWSCluster" 
E1031 18:41:17.758625       1 awscluster_controller.go:248] controller/awscluster "msg"="error deleting network" "error"="failed to delete vpc \"vpc-0792b7ba04b71f3da\": DependencyViolation: The vpc 'vpc-0792b7ba04b71f3da' has dependencies and cannot be deleted.\n\tstatus code: 400, request id: 64626725-ee55-45e5-ac71-575d9d03b988" "cluster"="gartner-group-mgmt" "name"="gartner-group-mgmt" "namespace"="default" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AWSCluster" 
E1031 18:41:17.974814       1 controller.go:317] controller/awscluster "msg"="Reconciler error" "error"="failed to delete vpc \"vpc-0792b7ba04b71f3da\": DependencyViolation: The vpc 'vpc-0792b7ba04b71f3da' has dependencies and cannot be deleted.\n\tstatus code: 400, request id: 64626725-ee55-45e5-ac71-575d9d03b988" "name"="gartner-group-mgmt" "namespace"="default" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AWSCluster" 
I1031 18:41:17.975511       1 awscluster_controller.go:209] controller/awscluster "msg"="Reconciling AWSCluster delete" "cluster"="gartner-group-mgmt" "name"="gartner-group-mgmt" "namespace"="default" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AWSCluster"`

Examining the environment with the AWS console shows no other resources except the VPC.

To complete the deletion of this cluster, we will have to delete the VPC that was created. Once done, the cluster is removed from the "kubectl get clusters" listing.

**What did you expect to happen:**
The cluster and all its resources would have been removed.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
This issue began to occur very recently within the last two weeks. Prior to that time, the cluster would delete as expected.

**Environment:**
Cluster controller running in EKS in the same region as the clusters that are created. Only tested with EC2 clusters. 

- Cluster-api-provider-aws version:  
capa-system                         infrastructure-aws      19d   InfrastructureProvider   aws           v1.5.0

- Kubernetes version: (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:47:25Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.13-eks-15b7512", GitCommit:"94138dfbea757d7aaf3b205419578ef186dd5efb", GitTreeState:"clean", BuildDate:"2022-08-31T19:15:48Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from `/etc/os-release`): 
`AME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"`

**Comment by pfcurtis** [comment]
`apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: gartner-group-mgmt
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: gartner-group-mgmt-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AWSCluster
    name: gartner-group-mgmt
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSCluster
metadata:
  name: gartner-group-mgmt
  namespace: default
spec:
  region: us-east-2
  sshKeyName: ""
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: gartner-group-mgmt-control-plane
  namespace: default
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-provider: aws
      controllerManager:
        extraArgs:
          cloud-provider: aws
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: aws
        name: '{{ ds.meta_data.local_hostname }}'
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: aws
        name: '{{ ds.meta_data.local_hostname }}'
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: AWSMachineTemplate
      name: gartner-group-mgmt-control-plane
  replicas: 1
  version: v1.23.8
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSMachineTemplate
metadata:
  name: gartner-group-mgmt-control-plane
  namespace: default
spec:
  template:
    spec:
      iamInstanceProfile: control-plane.cluster-api-provider-aws.sigs.k8s.io
      instanceType: t3.large
      sshKeyName: ""
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: gartner-group-mgmt-md-0
  namespace: default
spec:
  clusterName: gartner-group-mgmt
  replicas: 2
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: gartner-group-mgmt-md-0
      clusterName: gartner-group-mgmt
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AWSMachineTemplate
        name: gartner-group-mgmt-md-0
      version: v1.23.8
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSMachineTemplate
metadata:
  name: gartner-group-mgmt-md-0
  namespace: default
spec:
  template:
    spec:
      iamInstanceProfile: nodes.cluster-api-provider-aws.sigs.k8s.io
      instanceType: t3.medium
      sshKeyName: ""
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: gartner-group-mgmt-md-0
  namespace: default
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: aws
          name: '{{ ds.meta_data.local_hostname }}'`

**Comment by Skarlso** [comment]
Hey @pfcurtis 👋 :)

So, I've seen this happening once in a while. This occurs because it takes a bit of time to get rid of the NAT gateways, or the ENIs if I remember correctly. In both cases, however, eventually, capa was able to reconcile a delete.

Though I think I waited for a LOONG time, like, more than 10 minutes.

Did you, by any chance, wait that long for the cluster to be deleted?

**Comment by pfcurtis** [comment]
@Skarlso I waited several hours before manually removing the cluster. The issue is my case is isolated to the security group created for the ELB. If I manually delete the ELB SG, the provider completes the removal the VPC. The CAPI controller then shows the cluster has been deleted.

Both the Cluster and the AWSCluster are removed properly after deleting the ELB SG.

**Comment by Skarlso** [comment]
Thanks Paul. I'll look into it!

**Comment by Skarlso** [comment]
@pfcurtis Was this resolved in the end? :)

**Comment by pfcurtis** [comment]
The issue is still intermittent. On some occasions, the complete cluster will be deleted (including AWS resources not created by CAPA), and other times not. I still do not have a concrete case that is 100% reproducible.

**Comment by Skarlso** [comment]
Dang, that's a bummer. I tried to reproduce this locally, but didn't succeed. We'll keep this an try looking out for more information.

**Comment by dlipovetsky** [comment]
@pfcurtis Have you been able to  reproduce this issue with the External GC feature enabled? 

/triage needs-information

**Comment by pfcurtis** [comment]
As I was laid off from Weaveworks, I have not pursued this issue beyond late 2022. I will close it, and hope it has been resolved in newer releases.

**Comment by fiunchinho** [comment]
Can you close it @pfcurtis ?
